name: ci-cd
on: [push, pull_request]
jobs:
  ci:
    # set up operating system
    runs-on: ubuntu-latest

    # define job steps
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Install package
        run: python -m pip install -r requirements.txt

      - name: Testing
        run: echo Testing stage ...

      - name: Build documentation
        run: make html --directory docs/

  cd:
    # Only run this job if the 'ci' job passes
    needs: ci

    # Only run this job if new work is pushed to the 'main' branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install package
        run: python -m pip install -r requirements.txt

      - name: Use Python Semantic Release to prepare release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry run semantic-release publish
