name: ci-cd
on: [push, pull_request]
jobs:
  ci:
    # set up operating system
    runs-on: ubuntu-latest

    # define job steps
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Testing
        run: echo Testing stage ...

      - name: Build documentation
        run: make html --directory docs/
